#!/usr/bin/env bash
# Displays a list of currently running processes.
#   This processes must show all processes, for all users, including those
#   which might not have a TTY and display should be in user-oriented format.
#   The dispaly should show process hierarchy

ps -auxf
