#!/usr/bin/env bash
# Displays best scool 10 times:
#   "bad luck" for the 4th loop iteration
#   "good luck" for the 8th loop iteration
#   "Best School" for all other loop iterations

count=0

while [ $count -lt 10 ]
do
  if [ $count -eq 3 ]
  then
    echo "bad luck"
  elif [ $count -eq 7 ]
  then
    echo "good luck"vi
  else
    echo "Best School"
  fi
  (( count++ ))
done
