#!/usr/bin/env bash
# Displays in a list format the contents of the current directory .
#   displays only part of the name after the first dash. 

list=$(ls)
for i in $list; do
  echo "$i" | cut -d '-' -f2
done
